const rooms=[
  ['Номер делюкс с видом на сад',420,45,2,'Номер','Сад','Спокойное пространство в окружении тропического сада.'],
  ['Люкс с видом на океан',650,68,2,'Люкс','Океан','Панорамный вид на море и просторная частная терраса.'],
  ['Премиальный морской люкс',890,85,3,'Люкс','Океан','Современный прибрежный интерьер и бескрайний горизонт.'],
  ['Семейная резиденция',1100,110,5,'Резиденция','Сад','Просторные объединенные помещения для семейного отдыха.'],
  ['Представительский люкс с бассейном',1350,120,3,'Люкс','Бассейн','Частный бассейн и плавный переход между интерьером и террасой.'],
  ['Вилла у пляжа',2400,180,4,'Вилла','Пляж','Прямой выход к песку и абсолютная приватность на первой линии.'],
  ['Частная океанская вилла',3900,260,6,'Вилла','Океан','Три спальни, инфинити-бассейн и персональный батлер.'],
  ['Президентская вилла',8500,450,8,'Вилла','Океан','Самая исключительная частная резиденция курорта.']
];
const dining=[
  ['Azure Signature','Современная средиземноморская кухня','18:30–23:00','Элегантный курортный стиль','Крудо из сибаса · Ризотто с трюфелем'],
  ['Mediterranean Coast','Морепродукты и прибрежная кухня','12:00–22:30','Элегантный повседневный стиль','Осьминог на углях · Улов дня'],
  ['Sunset Lounge','Коктейли и легкие закуски','16:00–01:00','Курортный шик','Azure Spritz · Тарталетки с икрой']
];
const treatments=[
  ['Фирменный массаж',90,220,'Плавный ритуал для всего тела с растительными маслами.'],
  ['Глубокий массаж',75,195,'Направленное воздействие для снятия мышечного напряжения.'],
  ['Терапия горячими камнями',90,240,'Теплые вулканические камни восстанавливают баланс и спокойствие.'],
  ['Ритуал для лица',60,180,'Увлажнение и сияние с учетом особенностей вашей кожи.'],
  ['Океанский детокс',120,310,'Морские минералы, обертывание и восстанавливающий массаж.'],
  ['SPA-путешествие для двоих',150,620,'Ритуал в частном люксе и отдых с видом на океан.']
];
const experiences=[
  ['Частная яхта','Откройте скрытые бухты с личным капитаном и шеф-поваром.','4–8 часов',2200],
  ['Круиз на закате','Шампанское и путешествие вдоль побережья в золотой час.','2 часа',320],
  ['Дайвинг','Индивидуальное погружение к нетронутым рифам с инструктором.','3 часа',280],
  ['Экскурсия по острову','Особенный день среди пляжей, деревень и местных вкусов.','Весь день',450],
  ['Дегустация вин','Знакомство с выдающимися прибрежными винами вместе с сомелье.','90 минут',160],
  ['Ужин на частном пляже','Меню при свечах, созданное специально для двоих.','3 часа',650],
  ['Полет на вертолете','Захватывающее воздушное путешествие над островами и морем.','45 минут',1200],
  ['День восстановления','Продуманная программа движения, питания и восстановления.','Весь день',390]
];
function header(){return `<header class="header ${document.body.dataset.page==='home'?'':'inner'}"><div class="container header-in"><a class="logo" href="index.html">AZURE <i>RESORT</i></a><nav class="nav"><a href="index.html">Главная</a><a href="rooms.html">Номера и виллы</a><a href="dining.html">Рестораны</a><a href="spa.html">SPA</a><a href="experiences.html">Впечатления</a><a href="gallery.html">Галерея</a><a href="about.html">О курорте</a><a href="contact.html">Контакты</a></nav><a class="btn btn-gold cta" href="booking.html">Забронировать</a><button class="menu-btn" aria-label="Открыть меню">☰</button></div></header><nav class="mobile"><a href="index.html">Главная</a><a href="rooms.html">Номера и виллы</a><a href="dining.html">Рестораны</a><a href="spa.html">SPA</a><a href="experiences.html">Впечатления</a><a href="gallery.html">Галерея</a><a href="about.html">О курорте</a><a href="contact.html">Контакты</a><a class="btn btn-gold" href="booking.html">Забронировать</a></nav>`}
function footer(){return `<footer class="footer"><div class="container"><div class="footer-grid"><div><h3>AZURE RESORT</h3><p>Премиальный пляжный курорт и SPA</p></div><div><h4>НОМЕРА</h4><a href="rooms.html">Люксы</a><a href="room-detail.html">Виллы</a></div><div><h4>РЕСТОРАНЫ</h4><a href="dining.html">Гастрономия</a></div><div><h4>SPA</h4><a href="spa.html">Процедуры</a></div><div><h4>ВПЕЧАТЛЕНИЯ</h4><a href="experiences.html">Открыть</a></div><div><h4>О КУРОРТЕ</h4><a href="about.html">Наша история</a></div><div><h4>КОНТАКТЫ</h4><a href="mailto:almirkhialov@outlook.com">Почта</a><a href="https://t.me/almirkhialov">Telegram</a></div></div><div class="bottom">Концепция портфолио: Almir Khialov · Интерактивный сайт курорта</div></div></footer><div class="toast">Спасибо за запрос. Наша служба консьержей свяжется с вами в ближайшее время.</div>`}
function roomCards(list=rooms){return list.map((r,i)=>`<article class="card room-card reveal" data-type="${r[4]}" data-guests="${r[3]}" data-price="${r[1]}" data-view="${r[5]}"><div class="card-img"><img src="assets/images/${i%2?'villa':'hero'}.jpg" alt="${r[0]}"></div><div class="card-body"><div class="meta"><span>${r[2]} м² · гостей: ${r[3]}</span><span>Вид: ${r[5].toLowerCase()}</span></div><h3>${r[0]}</h3><p>${r[6]}</p><div class="amenities"><span>Кровать king-size</span><span>Частная терраса</span><span>Wi-Fi</span></div><div class="meta"><b class="price">От $${r[1].toLocaleString('ru-RU')} / ночь</b><a href="room-detail.html">Подробнее →</a></div></div></article>`).join('')}
function experienceCards(){return experiences.map((x,i)=>`<article class="card service-card reveal"><b>0${i+1}</b><h3>${x[0]}</h3><p>${x[1]}</p><div class="meta"><span>${x[2]}</span><span class="price">От $${x[3].toLocaleString('ru-RU')}</span></div><a class="btn" href="booking.html">Оставить запрос</a></article>`).join('')}
document.body.insertAdjacentHTML('afterbegin',header());document.body.insertAdjacentHTML('beforeend',footer());const menu=document.querySelector('.mobile');document.querySelector('.menu-btn').onclick=()=>{menu.classList.toggle('open');document.body.classList.toggle('lock')};addEventListener('scroll',()=>document.querySelector('.header').classList.toggle('scrolled',scrollY>30),{passive:true});const current=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===current));const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});function observe(){document.querySelectorAll('.reveal:not(.visible)').forEach(x=>io.observe(x))}observe();function toast(m){let t=document.querySelector('.toast');if(m)t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}document.addEventListener('click',e=>{let f=e.target.closest('.faq button');if(f)f.parentElement.classList.toggle('open');if(e.target.closest('.demo-submit')){e.preventDefault();toast()}});
function filterRooms(){let t=document.querySelector('[name=roomType]')?.value||'',g=+(document.querySelector('[name=guests]')?.value||0),p=+(document.querySelector('[name=maxPrice]')?.value||0),v=document.querySelector('[name=viewType]')?.value||'',s=document.querySelector('[name=sort]')?.value||'';let cards=[...document.querySelectorAll('.room-card')];cards.forEach(c=>c.classList.toggle('hidden',!((!t||c.dataset.type===t)&&(!g||+c.dataset.guests>=g)&&(!p||+c.dataset.price<=p)&&(!v||c.dataset.view===v))));if(s==='low'||s==='high')cards.sort((a,b)=>s==='low'?a.dataset.price-b.dataset.price:b.dataset.price-a.dataset.price).forEach(c=>c.parentElement.appendChild(c))}document.addEventListener('change',e=>{if(e.target.closest('.room-filter'))filterRooms()});
document.addEventListener('click',e=>{let tab=e.target.closest('.tabs button');if(tab){tab.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));tab.classList.add('active');let c=tab.dataset.category;document.querySelectorAll('.gallery figure').forEach(x=>x.classList.toggle('hidden',c&&c!=='Все'&&x.dataset.category!==c))}});
let step=1,reservation={room:'',checkin:'',checkout:'',guests:'2 взрослых'};function bookingStep(n){step=Math.max(1,Math.min(5,n));document.querySelectorAll('.booking-step').forEach((x,i)=>x.classList.toggle('active',i===step-1));document.querySelectorAll('.steps i').forEach((x,i)=>x.classList.toggle('active',i<step));document.querySelector('.prev-step')?.toggleAttribute('disabled',step===1);document.querySelector('.next-step')?.classList.toggle('hidden',step===5);if(step===5)summary()}function summary(){let nights=reservation.checkin&&reservation.checkout?Math.max(1,Math.round((new Date(reservation.checkout)-new Date(reservation.checkin))/86400000)):1,room=rooms.find(r=>r[0]===reservation.room),total=(room?.[1]||0)*nights,map={room:reservation.room||'Не выбран',dates:reservation.checkin&&reservation.checkout?reservation.checkin+' — '+reservation.checkout:'Не выбраны',guests:reservation.guests,total:total?'$'+total.toLocaleString('ru-RU'):'—'};document.querySelectorAll('[data-summary]').forEach(x=>x.textContent=map[x.dataset.summary])}function valid(){if(step===1&&!reservation.room)return toast('Выберите номер, чтобы продолжить.'),false;if(step===2&&(!reservation.checkin||!reservation.checkout))return toast('Укажите даты заезда и выезда.'),false;if(step===4&&!document.querySelector('form')?.reportValidity())return false;return true}document.addEventListener('click',e=>{let c=e.target.closest('.choice');if(c){c.parentElement.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');reservation[c.dataset.key]=c.dataset.value}if(e.target.closest('.next-step')&&valid())bookingStep(step+1);if(e.target.closest('.prev-step'))bookingStep(step-1);if(e.target.closest('.finish-booking')){e.preventDefault();toast();bookingStep(5)}if(e.target.closest('.reset-booking')){reservation={room:'',checkin:'',checkout:'',guests:'2 взрослых'};document.querySelector('form')?.reset();document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));bookingStep(1)}});document.addEventListener('change',e=>{if(e.target.matches('[name=checkin]'))reservation.checkin=e.target.value;if(e.target.matches('[name=checkout]'))reservation.checkout=e.target.value;if(e.target.matches('[name=bookingGuests]'))reservation.guests=e.target.value});window.bookingStep=bookingStep;
