const cities=[['Istanbul','Два континента и утро на Босфоре','istanbul','3 маршрута','12 мест','8 ресторанов'],['Tbilisi','Балконы, холмы и длинные ужины','tbilisi','4 маршрута','16 мест','11 ресторанов'],['Antalya','Море, старый город и закаты','antalya','3 маршрута','14 мест','9 ресторанов'],['Paris','Кварталы для прогулок без спешки','paris','6 маршрутов','24 места','18 ресторанов'],['Tokyo','Тихие сады и энергия ночного города','tokyo','5 маршрутов','21 место','15 ресторанов'],['Barcelona','Архитектура, море и поздние завтраки','barcelona','4 маршрута','18 мест','13 ресторанов']];
document.querySelector('#destination-track').innerHTML=cities.map(c=>`<article class="destination-card"><img src="assets/images/${c[2]}.jpg" alt="${c[0]}"><div class="city-info"><small>Atlas destination</small><h3>${c[0]}</h3><p>${c[1]}</p><div class="city-meta"><span>${c[3]}</span><span>${c[4]}</span><span>${c[5]}</span></div></div></article>`).join('');
const places=[['Galata Rooftop','Стамбул','Viewpoints','Панорама Босфора без очередей.','4.9','₽₽','Viewpoints'],['Kronotrop','Стамбул','Food','Спешелти-кофе в тихом переулке.','4.8','₽₽','Food'],['Fabrika Courtyard','Тбилиси','Culture','Двор, галереи и локальные проекты.','4.7','₽','Culture'],['Narikala at Dawn','Тбилиси','Hidden','Крепость до прихода города.','4.9','Бесплатно','Hidden'],['Kaleici Garden','Анталья','Romantic','Ужин в саду старого города.','4.8','₽₽₽','Romantic'],['Canal Saint-Martin','Париж','Family','Прогулка у воды и пикник.','4.7','Бесплатно','Family'],['Yanaka Ginza','Токио','Hidden','Старый Токио, лавки и кошки.','4.9','₽','Hidden'],['El Born Night','Барселона','Night','Тапас и маленькие бары после заката.','4.8','₽₽','Night']];
const filters=['All','Food','Viewpoints','Culture','Romantic','Hidden','Family','Night'];const filterBox=document.querySelector('#place-filters'),placeGrid=document.querySelector('#place-grid');filterBox.innerHTML=filters.map((f,i)=>`<button class="${i?'':'active'}" data-filter="${f}">${f}</button>`).join('');placeGrid.innerHTML=places.map((p,i)=>`<article class="place-card reveal" data-cat="${p[6]}"><small>${p[1]} · ${p[2]}</small><h3>${p[0]}</h3><p>${p[3]}</p><div class="place-bottom"><span>★ ${p[4]} · ${p[5]}</span><button data-add="${i}" aria-label="Добавить ${p[0]} в маршрут">+</button></div></article>`).join('');filterBox.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;filterBox.querySelector('.active').classList.remove('active');b.classList.add('active');document.querySelectorAll('.place-card').forEach(c=>c.classList.toggle('hidden',b.dataset.filter!=='All'&&c.dataset.cat!==b.dataset.filter))});
const routes=[['Стамбул за 1 день','8 часов','7 мест','8,4 км','Гастрономия'],['Романтичный Тбилиси','6 часов','6 мест','5,2 км','Для двоих'],['Анталья: море, еда и закат','10 часов','8 мест','12 км','Море'],['Париж без спешки','2 дня','12 мест','16 км','Slow travel']];document.querySelector('#route-grid').innerHTML=routes.map(r=>`<article class="route-card reveal"><small>Atlas route</small><h3>${r[0]}</h3><p>Продуманный ритм дня с паузами, локальной едой и лучшим светом для прогулки.</p><div class="meta"><span>${r[1]}</span><span>${r[2]}</span><span>${r[3]}</span><span>${r[4]}</span></div></article>`).join('');
const toast=document.querySelector('.toast');let timer;function notify(t){toast.textContent=t;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),2200)}document.addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(b)notify(`${places[b.dataset.add][0]} добавлено в маршрут`)});
document.querySelector('#trip-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),city=d.get('city'),mood=d.get('mood'),time=d.get('time');e.currentTarget.querySelector('.trip-result').textContent=`Готово: ${city} · ${mood} · ${time}. Маршрут включает 5 мест и 2 гастрономические остановки.`;notify('Маршрут собран')});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal,.map').forEach(el=>observer.observe(el));
const header=document.querySelector('header');addEventListener('scroll',()=>{header.classList.toggle('scrolled',scrollY>40);if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const hero=document.querySelector('.hero-bg');hero.style.transform=`scale(1.05) translateY(${Math.min(scrollY*.035,25)}px)`}},{passive:true});
const burger=document.querySelector('.burger'),mobile=document.querySelector('.mobile-menu');burger.addEventListener('click',()=>mobile.classList.toggle('open'));mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobile.classList.remove('open')));
if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
addEventListener('load',()=>setTimeout(()=>document.querySelector('.loader').classList.add('done'),350));
